name = "micro-communication-chat"
compatibility_date = "2025-07-26"
main = "src/index.ts"

[[durable_objects.bindings]]
name = "USECASE"
class_name = "UseCase"

[[migrations]]
tag = "v2"
new_sqlite_classes = ["UseCase"]

[[rules]]
type = "Text"
globs = ["**/*.sql"]
fallthrough = true
