packages:
  - ./workspaces/*
  - ./docs

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
  - workerd

patchedDependencies:
  drizzle-orm: patches/drizzle-orm.patch

savePrefix: ""
